### ISSUE TITLE
Update TSC Repository To Reflect TAC

### ISSUE THREAD

**Issue by bensternthal** [chipsalliance/tac#146]
Below are the updated & changes needed so that this TSC repository accurately reflects the new tac:

### Renaming Of Repo
- [x] Rename this repo TAC
   - [x]  Update [Website Repo docs and code](https://github.com/chipsalliance/chips-alliance-website/blob/main/README.md) to reference TAC repo
   - [x]  Update website workflows

### Website Updates
- [x] https://github.com/chipsalliance/chips-alliance-website/blob/main/content/getting-started.md
- [x] https://github.com/chipsalliance/chips-alliance-website/blob/main/content/about/faq.md
- [x] https://github.com/chipsalliance/chips-alliance-website/blob/main/content/about/governance.md
 
### Updating Repo Documents
 - [x]  Update chipsalliance/tsc/README.md)
 - [x] Update  chipsalliance/tsc/CONTRIBUTING.md
 - [x] Update chipsalliance/tsc/STAGING_PROCESS.md
 - [x] Update chipsalliance/tsc/projects/MISSION_STATEMENT_TEMPLATE.md
 - [x] Update/REmove technical charter template
 - [x] Update chipsalliance/tsc/projects/README.md (typo line 9)
 - [x] Update chipsalliance/tsc/proposals/stage-2/README.md
 - [x] Update chipsalliance/tsc/projects/templates/project-application-template.yml (comment line 11)
 - [x] Remove  [Technical Charter](https://github.com/chipsalliance/tsc/blob/main/CHIPS_Alliance-Technical_Charter.pdf)

## Other

- [x] Audit security@lists.chipsalliance.org
- [x] Check copyright statement contained in readme
